---
- name: Write cert files
  copy: 
    content: "{{cert.content}}"
    dest: "{{splunk_home}}/{{cert.name}}"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}" 
  with_items: "{{ splunk_certs }}"
  no_log: "{{ censor_secrets }}"
  loop_control:
    loop_var: cert
  when: splunk_certs is defined

- name: setup {{ item }}.conf 
  template: 
    src: splunk_home/etc/system/local/{{ item }}.conf.j2
    dest: "{{ splunk_home }}/etc/system/local/{{ item }}.conf"
    owner: "{{ splunk_user }}"
    group: "{{ splunk_group }}" 
    mode: 600
  with_items:
    - web
    - transforms
    - server
    - limits
    - authorize
    - passwords
    - inputs
    - outputs
    - indexes
    - props
    - fields
  notify:
    - restart splunk
