---
- name: set splunk checksum
  set_fact:
    splunk_checksum: "{{ 'sha1' if splunk_checksums[splunk_version]|length == 40 else 'sha256' }}:{{ splunk_checksums[splunk_version] }}"
  when:
    - splunk_verify_checksum|bool
    - splunk_file_checksum is not defined
    - splunk_file in splunk_checksums

- name: set local filename
  set_fact:
    splunk_filepath: /usr/local/src/{{ splunk_file }}

- name: download splunk
  get_url:
    url: "{{ splunk_download_url }}"
    dest: "{{ splunk_filepath }}"
    checksum: "{{ splunk_checksum|default(omit) }}"

