---
- name: set splunk checksum
  set_fact:
    splunk_checksum: "{{ 'sha1' if splunk_checksums[splunk_version]|length == 40 else 'sha256' }}:{{ splunk_checksums[splunk_version] }}"
  when:
    - splunk_verify_checksum|bool
    - splunk_file_checksum is not defined
    - splunk_file in splunk_checksums

- name: set local filename
  set_fact:
    splunk_filepath: /usr/local/src/{{ splunk_file }}

- name: download splunk
  get_url:
    url: "{{ splunk_download_url }}"
    dest: "{{ splunk_filepath }}"
    checksum: "{{ splunk_checksum|default(omit) }}"
    
- name: checking if splunk is installed
  stat: path={{splunk_home}}
  register: splunk_path

- block:
  - name: extract splunk
    unarchive:
      src: "{{ splunk_filepath }}"
      dest: /opt/
      copy: no
      owner: "{{ splunk_user }}"
      group: "{{ splunk_group }}"
  - name: Generate user-seed.conf
    ini_file:
      owner: "{{ splunk_user }}"
      group: "{{ splunk_group }}"
      dest: "{{ splunk_home }}/etc/system/local/user-seed.conf"
      section: user_info
      option: "{{ item.opt }}"
      value: "{{ item.val }}"
    with_items:
      - { opt: 'USERNAME', val: 'admin' }
      - { opt: 'PASSWORD', val: 'changeme' }
    loop_control:
      label: "{{ item.opt }}"
    no_log: "{{ censor_secrets }}"
#  - name: accept license and start splunk
#    shell: "{{splunk_home}}/bin/splunk start --accept-license --answer-yes --no-prompt"
  - name: enable boot-start
    shell: "{{splunk_home}}/bin/splunk enable boot-start --accept-license --answer-yes --no-prompt"
  - name: touch ui so it does not ask for the password to be changed
    file: 
      path: "{{splunk_home}}/etc/.ui_login"
      state: touch
      owner: "{{ splunk_user }}"
      group: "{{ splunk_group }}" 
  - name: Set SPLUNK_HOME
    template:
      src: etc/profile.d/splunk_home.sh.j2
      dest: /etc/profile.d/splunk_home.sh
      owner: "{{ splunk_user }}"
      group: "{{ splunk_group }}" 
      mode: 0644
  - name: restart splunk after initial install
    service:
      name: Splunkd
      state: restarted
  become: true
  when: splunk_path.stat.exists == false


