---
- name: checking if splunk is install
  stat: path=/opt/splunk
  register: splunk_path

- block:
  - name: extract splunk
    unarchive:
      src: "{{ splunk_filepath }}"
      dest: /opt/
      copy: no
      owner: "{{ splunk_user }}"
      group: "{{ splunk_group }}" 
  - name: accept license and start splunk
    shell: /opt/splunk/bin/splunk start --accept-license
  - name: enable boot-start
    shell: /opt/splunk/bin/splunk enable boot-start
  - name: make /etc/init.d/splunk executable
    file: 
      path: /etc/init.d/splunk
      mode: 755
  - name: touch ui so it does not ask for the password to be changed
    shell: touch /opt/splunk/etc/.ui_login
  become: true
  when: splunk_path.stat.exists == false
